services:
  # Monolithic Web Service (Backend + Frontend)
  - type: web
    name: nsm-portal
    env: node
    plan: free
    buildCommand: npm install --prefix frontend --production=false && npm run build --prefix frontend && npm install --prefix backend --production=false
    startCommand: TS_NODE_PROJECT=./backend/tsconfig.json node -r ./backend/node_modules/ts-node/register ./backend/src/index.ts
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
