services:
  # Monolithic Web Service (Backend + Frontend)
  - type: web
    name: nsm-portal
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend && npx --prefix backend prisma generate --schema=backend/prisma/schema.prisma && npx --prefix backend prisma db push --schema=backend/prisma/schema.prisma --accept-data-loss
    startCommand: npx ts-node backend/src/index.ts
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
